
title: Toddwords.com | Homepage of web poet and digital artist Todd Anderson
desctiption: Homepage of web poet and digital artist Todd Anderson
url: http://toddwords.com/
permalink: ':title/'
repository: toddwords/toddwords.github.io
markdown: kramdown
baseurl: ""


sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-90458581-1

# Comments
disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

gems: [jekyll-paginate, jekyll-seo-tag]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "todd"
      evergreen: 9999